export interface AITool {
  name: string;
  slug: string;
  category: string;
  description: string;
  url: string;
  pricing?: "Free" | "Freemium" | "Paid";
  logo?: string;
  tags?: string[];
  featured?: boolean;
  trending?: boolean;
  rating?: number;
  addedDate?: string;
}

export interface BlogPost {
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  date: string;
  author: string;
  category: string;
  image?: string;
  tags?: string[];
}

export const AI_TOOLS: AITool[] = [
  { 
    name: "ChatGPT", 
    slug: "chatgpt",
    category: "Chatbots", 
    description: "Advanced conversational AI by OpenAI that can help with writing, coding, and general knowledge.", 
    url: "https://chat.openai.com",
    pricing: "Freemium",
    featured: true,
    trending: true,
    rating: 4.9,
    tags: ["OpenAI", "LLM", "Assistant"]
  },
  { 
    name: "Midjourney", 
    slug: "midjourney",
    category: "Image Generation AI", 
    description: "High-quality AI image generation via Discord. Known for its artistic and highly detailed outputs.", 
    url: "https://midjourney.com",
    pricing: "Paid",
    featured: true,
    trending: true,
    rating: 4.8,
    tags: ["Art", "Generative", "Discord"]
  },
  { 
    name: "Claude", 
    slug: "claude",
    category: "Chatbots", 
    description: "Next-generation AI assistant by Anthropic, designed to be helpful, harmless, and honest.", 
    url: "https://claude.ai",
    pricing: "Freemium",
    featured: true,
    rating: 4.7,
    tags: ["Anthropic", "Safety", "LLM"]
  },
  { 
    name: "Gemini", 
    slug: "gemini",
    category: "Chatbots", 
    description: "Google's most capable and general AI model, integrated across Google products.", 
    url: "https://gemini.google.com",
    pricing: "Freemium",
    trending: true,
    rating: 4.6,
    tags: ["Google", "Multimodal", "LLM"]
  },
  { name: "DALL·E", slug: "dall-e", category: "Image Generation AI", description: "OpenAI's system that creates realistic images from text", url: "https://openai.com/dall-e" },
  { name: "Canva AI", slug: "canva-ai", category: "Design AI", description: "Magic Studio tools for effortless design creation", url: "https://www.canva.com" },
  { name: "Grammarly", slug: "grammarly", category: "Writing AI", description: "AI-powered writing assistant and grammar checker", url: "https://www.grammarly.com" },
  { name: "Notion AI", slug: "notion-ai", category: "Productivity AI", description: "AI integrated directly into your Notion workspace", url: "https://www.notion.so" },
  { name: "Jasper AI", slug: "jasper-ai", category: "Writing AI", description: "Enterprise AI platform for content creation", url: "https://www.jasper.ai" },
  { name: "Copy.ai", slug: "copy-ai", category: "Writing AI", description: "AI platform for faster marketing copy and content", url: "https://www.copy.ai" },
  { name: "Writesonic", slug: "writesonic", category: "Writing AI", description: "AI writer for blogs, ads, and product descriptions", url: "https://writesonic.com" },
  { name: "Rytr", slug: "rytr", category: "Writing AI", description: "Affordable AI writing assistant for content creators", url: "https://rytr.me" },
  { name: "Runway ML", slug: "runway-ml", category: "Video AI", description: "Next-generation creative tools for video generation", url: "https://runwayml.com" },
  { name: "Pictory", slug: "pictory", category: "Video AI", description: "Automatically create short, highly-sharable branded videos", url: "https://pictory.ai" },
  { name: "Synthesia", slug: "synthesia", category: "Video AI", description: "Create professional videos with AI avatars", url: "https://www.synthesia.io" },
  { name: "Leonardo AI", slug: "leonardo-ai", category: "Image Generation AI", description: "Generative AI platform for creators and studios", url: "https://leonardo.ai" },
  { name: "Descript", slug: "descript", category: "Audio AI", description: "AI-powered video and podcast editing tool", url: "https://www.descript.com" },
  { name: "Murf AI", slug: "murf-ai", category: "Audio AI", description: "Versatile AI voice generator and text-to-speech", url: "https://murf.ai" },
  { name: "Luma AI", slug: "luma-ai", category: "Video AI", description: "High-quality 3D and video generation from text", url: "https://lumalabs.ai" },
  { name: "Durable AI", slug: "durable-ai", category: "Automation AI", description: "AI website builder that creates a site in 30 seconds", url: "https://durable.co" },
  { name: "Tome AI", slug: "tome-ai", category: "Productivity AI", description: "AI-powered storytelling and presentation tool", url: "https://tome.app" },
  { name: "Beautiful AI", slug: "beautiful-ai", category: "Design AI", description: "Presentation software that designs itself", url: "https://www.beautiful.ai" },
  { name: "Gamma AI", slug: "gamma-ai", category: "Design AI", description: "Create presentations, docs, and sites with AI", url: "https://gamma.app" },
  { name: "Otter AI", slug: "otter-ai", category: "Productivity AI", description: "AI meeting assistant for transcription and notes", url: "https://otter.ai" },
  { name: "ElevenLabs", slug: "elevenlabs", category: "Audio AI", description: "Most realistic AI speech and voice cloning", url: "https://elevenlabs.io" },
  { name: "Replit AI", slug: "replit-ai", category: "Coding AI", description: "AI-powered coding environment and assistant", url: "https://replit.com" },
  { name: "Cursor AI", slug: "cursor-ai", category: "Coding AI", description: "The AI-first code editor for faster development", url: "https://cursor.sh" },
  { name: "Tabnine", slug: "tabnine", category: "Coding AI", description: "AI assistant for software developers", url: "https://www.tabnine.com" },
  { name: "Codeium", slug: "codeium", category: "Coding AI", description: "Free AI-powered code acceleration toolkit", url: "https://codeium.com" },
  { name: "Phind", slug: "phind", category: "Coding AI", description: "AI search engine for developers", url: "https://www.phind.com" },
  { name: "Perplexity AI", slug: "perplexity-ai", category: "Chatbots", description: "AI-powered search engine and answer engine", url: "https://www.perplexity.ai" },
  { name: "Poe AI", slug: "poe-ai", category: "Chatbots", description: "Platform to access multiple AI models easily", url: "https://poe.com" },
  { name: "Quillbot", slug: "quillbot", category: "Writing AI", description: "AI paraphrasing tool and writing enhancer", url: "https://quillbot.com" },
  { name: "Wordtune", slug: "wordtune", category: "Writing AI", description: "AI writing companion that helps rephrase sentences", url: "https://www.wordtune.com" },
  { name: "Looka AI", slug: "looka-ai", category: "Design AI", description: "AI-powered logo maker and brand builder", url: "https://looka.com" },
  { name: "Brandmark", slug: "brandmark", category: "Design AI", description: "Create a unique logo and brand identity with AI", url: "https://brandmark.io" },
  { name: "Remove.bg", slug: "remove-bg", category: "Design AI", description: "Remove image backgrounds automatically with AI", url: "https://www.remove.bg" },
  { name: "Cleanup Pictures", slug: "cleanup-pictures", category: "Design AI", description: "Remove objects, people, or text from images", url: "https://cleanup.pictures" },
  { name: "Upscale Media", slug: "upscale-media", category: "Design AI", description: "Upscale and enhance images with AI", url: "https://www.upscale.media" },
  { name: "PlayHT", slug: "playht", category: "Audio AI", description: "AI voice generator and realistic text-to-speech", url: "https://play.ht" },
  { name: "Soundraw", slug: "soundraw", category: "Audio AI", description: "AI music generator for content creators", url: "https://soundraw.io" },
  { name: "Boomy", slug: "boomy", category: "Audio AI", description: "Create and share generative music instantly", url: "https://boomy.com" },
  { name: "Kaiber AI", slug: "kaiber-ai", category: "Video AI", description: "AI creative engine for video generation", url: "https://kaiber.ai" },
  { name: "Opus Clip", slug: "opus-clip", category: "Video AI", description: "Turn long videos into short viral clips with AI", url: "https://opus.pro" },
  { name: "CapCut AI", slug: "capcut-ai", category: "Video AI", description: "AI-powered video editing features for social media", url: "https://www.capcut.com" },
  { name: "Fireflies AI", slug: "fireflies-ai", category: "Productivity AI", description: "AI meeting assistant that records and transcribes", url: "https://fireflies.ai" },
  { name: "Taskade AI", slug: "taskade-ai", category: "Productivity AI", description: "AI-powered productivity and collaboration platform", url: "https://taskade.com" },
  { name: "Zapier AI", slug: "zapier-ai", category: "Automation AI", description: "AI-powered automation for your workflows", url: "https://zapier.com" },
  { name: "Make AI", slug: "make-ai", category: "Automation AI", description: "Visual automation platform with AI capabilities", url: "https://www.make.com" },
  { name: "Browse AI", slug: "browse-ai", category: "Automation AI", description: "Train a robot to scrape and monitor websites", url: "https://www.browse.ai" },
  { name: "AgentGPT", slug: "agentgpt", category: "Automation AI", description: "Configure and deploy autonomous AI agents", url: "https://agentgpt.reworkd.ai" },
  { name: "AutoGPT", slug: "auto-gpt", category: "Automation AI", description: "An experimental open-source autonomous AI agent", url: "https://github.com/Significant-Gravitas/AutoGPT" },
  { name: "Hugging Face", slug: "hugging-face", category: "Coding AI", description: "The platform for machine learning and AI models", url: "https://huggingface.co" },
  { name: "Replicate", slug: "replicate", category: "Coding AI", description: "Run machine learning models in the cloud", url: "https://replicate.com" },
  { name: "Stability AI", slug: "stability-ai", category: "Image Generation AI", description: "Open-source generative AI company", url: "https://stability.ai" },
  { name: "DreamStudio", slug: "dreamstudio", category: "Image Generation AI", description: "Official interface for Stable Diffusion models", url: "https://dreamstudio.ai" },
  { name: "Krea AI", slug: "krea-ai", category: "Image Generation AI", description: "Real-time generative AI for creative professionals", url: "https://krea.ai" },
  { name: "Ideogram AI", slug: "ideogram-ai", category: "Image Generation AI", description: "AI that excels at generating text within images", url: "https://ideogram.ai" },
  { name: "Pixlr AI", slug: "pixlr-ai", category: "Design AI", description: "AI-powered photo editor and design tools", url: "https://pixlr.com" },
  { name: "Hotpot AI", slug: "hotpot-ai", category: "Design AI", description: "AI tools for graphics, pictures, and writing", url: "https://hotpot.ai" },
  { name: "DeepL", slug: "deepl", category: "Writing AI", description: "World's most accurate AI translator", url: "https://www.deepl.com" },
  { name: "Character AI", slug: "character-ai", category: "Chatbots", description: "Chat with AI-powered fictional characters", url: "https://character.ai" },
  { name: "Janitor AI", slug: "janitor-ai", category: "Chatbots", description: "Platform for roleplay and character interaction", url: "https://janitorai.com" },
  { name: "NovelAI", slug: "novel-ai", category: "Writing AI", description: "AI-assisted storytelling and text generation", url: "https://novelai.net" },
  { name: "Sudowrite", slug: "sudowrite", category: "Writing AI", description: "The AI writing partner for fiction authors", url: "https://www.sudowrite.com" },
  { name: "Stockimg AI", slug: "stockimg-ai", category: "Design AI", description: "AI-generated stock images, logos, and posters", url: "https://stockimg.ai" },
  { name: "Artbreeder", slug: "artbreeder", category: "Image Generation AI", description: "Collaborative AI tool for creating unique art", url: "https://www.artbreeder.com" },
  { name: "NightCafe", slug: "nightcafe", category: "Image Generation AI", description: "AI art generator with multiple creation methods", url: "https://nightcafe.studio" },
  { name: "DeepAI", slug: "deepai", category: "Image Generation AI", description: "AI tools for naturally creative people", url: "https://deepai.org" },
  { name: "PromptBase", slug: "promptbase", category: "Marketing AI", description: "Marketplace for high-quality AI prompts", url: "https://promptbase.com" },
  { name: "PromptHero", slug: "prompthero", category: "Marketing AI", description: "Search engine for AI prompts and images", url: "https://prompthero.com" },
  { name: "AI Dungeon", slug: "ai-dungeon", category: "Chatbots", description: "Infinite AI-generated text adventure game", url: "https://aidungeon.io" },
  { name: "Voiceflow", slug: "voiceflow", category: "Automation AI", description: "Build and deploy AI agents for any channel", url: "https://www.voiceflow.com" },
  { name: "FlowGPT", slug: "flowgpt", category: "Marketing AI", description: "Community platform for sharing AI prompts", url: "https://flowgpt.com" },
  { name: "PromptPerfect", slug: "promptperfect", category: "Marketing AI", description: "Optimize your prompts for better AI results", url: "https://promptperfect.jina.ai" },
  { name: "AIPRM", slug: "aiprm", category: "Marketing AI", description: "Curated prompt templates for ChatGPT", url: "https://www.aiprm.com" },
  { name: "Superhuman AI", slug: "superhuman-ai", category: "Productivity AI", description: "The fastest email experience, now with AI", url: "https://www.superhuman.com" },
  { name: "Compose AI", slug: "compose-ai", category: "Writing AI", description: "AI extension that automates your writing", url: "https://www.compose.ai" },
  { name: "Anyword", slug: "anyword", category: "Marketing AI", description: "AI copywriter that predicts performance", url: "https://anyword.com" },
  { name: "Ocoya", slug: "ocoya", category: "Marketing AI", description: "AI platform for social media content creation", url: "https://www.ocoya.com" },
  { name: "Predis AI", slug: "predis-ai", category: "Marketing AI", description: "AI social media post generator and scheduler", url: "https://predis.ai" },
  { name: "Taplio AI", slug: "taplio-ai", category: "Marketing AI", description: "AI-powered tool for LinkedIn growth", url: "https://taplio.com" },
  { name: "AdCreative AI", slug: "adcreative-ai", category: "Marketing AI", description: "Generate high-converting ad creatives with AI", url: "https://www.adcreative.ai" },
  { name: "HeyGen", slug: "heygen", category: "Video AI", description: "AI video generation for business and marketing", url: "https://www.heygen.com" },
  { name: "InVideo", slug: "invideo", category: "Video AI", description: "AI-powered online video editor and creator", url: "https://invideo.io" },
  { name: "Fliki", slug: "fliki", category: "Video AI", description: "Turn text into videos with AI voices", url: "https://fliki.ai" },
  { name: "Krisp", slug: "krisp", category: "Audio AI", description: "AI noise cancellation for online meetings", url: "https://krisp.ai" },
  { name: "Scribe", slug: "scribe", category: "Automation AI", description: "AI tool that documents your processes instantly", url: "https://getscribe.ai" },
  { name: "Mem", slug: "mem", category: "Productivity AI", description: "AI-powered workspace for your notes and thoughts", url: "https://mem.ai" },
  { name: "Rewind", slug: "rewind", category: "Productivity AI", description: "The search engine for your life", url: "https://www.rewind.ai" },
  { name: "Glean", slug: "glean", category: "Productivity AI", description: "Enterprise search and knowledge management", url: "https://www.glean.com" },
  { name: "Gong", slug: "gong", category: "Marketing AI", description: "Revenue intelligence platform powered by AI", url: "https://www.gong.io" },
  { name: "Chorus", slug: "chorus", category: "Marketing AI", description: "Conversation intelligence for sales teams", url: "https://www.chorus.ai" },
  { name: "Lavender", slug: "lavender", category: "Marketing AI", description: "AI email assistant for sales professionals", url: "https://www.lavender.ai" },
  { name: "Regie.ai", slug: "regie-ai", category: "Marketing AI", description: "AI content platform for modern sales teams", url: "https://www.regie.ai" },
  { name: "6sense", slug: "6sense", category: "Marketing AI", description: "AI-driven account-based marketing platform", url: "https://6sense.com" },
  { name: "Demandbase", slug: "demandbase", category: "Marketing AI", description: "B2B go-to-market platform with AI", url: "https://www.demandbase.com" },
  { name: "Drift", slug: "drift", category: "Marketing AI", description: "AI-powered conversational marketing platform", url: "https://www.drift.com" },
  { name: "Intercom", slug: "intercom", category: "Marketing AI", description: "AI-powered customer service platform", url: "https://www.intercom.com" },
  { name: "Zendesk", slug: "zendesk", category: "Marketing AI", description: "AI-enhanced customer support software", url: "https://www.zendesk.com" },
  { name: "Salesforce Einstein", slug: "salesforce-einstein", category: "Automation AI", description: "AI built into the world's #1 CRM", url: "https://www.salesforce.com/products/einstein/overview/" },
  { name: "Microsoft Copilot", slug: "microsoft-copilot", category: "Productivity AI", description: "Your everyday AI companion by Microsoft", url: "https://www.microsoft.com/en-us/microsoft-copilot" },
  { name: "Adobe Firefly", slug: "adobe-firefly", category: "Design AI", description: "Generative AI for creative expression", url: "https://www.adobe.com/sensei/generative-ai/firefly.html" },
  { name: "Framer AI", slug: "framer-ai", category: "Design AI", description: "Design and publish websites with AI", url: "https://www.framer.com/ai/" },
  { name: "Wix ADI", slug: "wix-adi", category: "Design AI", description: "Artificial Design Intelligence for websites", url: "https://www.wix.com" },
  { name: "10Web", slug: "10web", category: "Automation AI", description: "AI-powered WordPress platform and builder", url: "https://10web.io" },
  { name: "Suno AI", slug: "suno-ai", category: "Audio AI", description: "Generate full songs with vocals and instrumentation", url: "https://suno.com" },
  { name: "Udio", slug: "udio", category: "Audio AI", description: "AI music creation platform for high-fidelity tracks", url: "https://udio.com" },
  { name: "Veed.io", slug: "veed-io", category: "Video AI", description: "AI-powered online video editor for social media", url: "https://www.veed.io" },
  { name: "Sora", slug: "sora", category: "Video AI", description: "OpenAI's text-to-video model for realistic scenes", url: "https://openai.com/sora" },
  { name: "Pika Labs", slug: "pika-labs", category: "Video AI", description: "Idea-to-video platform for creative animation", url: "https://pika.art" },
  { name: "Relume", slug: "relume", category: "Design AI", description: "AI website builder and sitemap generator", url: "https://www.relume.io" },
  { name: "Galileo AI", slug: "galileo-ai", category: "Design AI", description: "Generative AI for interface design and UI/UX", url: "https://www.usegalileo.ai" },
  { name: "Uizard", slug: "uizard", category: "Design AI", description: "AI-powered design tool for apps and websites", url: "https://uizard.io" },
  { name: "Visily", slug: "visily", category: "Design AI", description: "AI-powered wireframing and prototyping tool", url: "https://www.visily.ai" },
  { name: "Magician", slug: "magician", category: "Design AI", description: "AI plugin for Figma to generate icons and copy", url: "https://magician.design" },
  { name: "Dora AI", slug: "dora-ai", category: "Design AI", description: "AI-powered 3D website builder and animation", url: "https://www.dora.run" },
  { name: "Spline AI", slug: "spline-ai", category: "Design AI", description: "Generate 3D objects and scenes with text prompts", url: "https://spline.design/ai" },
  { name: "Mintlify", slug: "mintlify", category: "Coding AI", description: "AI-powered documentation for software teams", url: "https://mintlify.com" },
  { name: "Mutable.ai", slug: "mutable-ai", category: "Coding AI", description: "AI-accelerated software development platform", url: "https://mutable.ai" },
  { name: "Sourcegraph Cody", slug: "sourcegraph-cody", category: "Coding AI", description: "AI coding assistant that understands your codebase", url: "https://about.sourcegraph.com/cody" },
  { name: "Amazon CodeWhisperer", slug: "amazon-codewhisperer", category: "Coding AI", description: "AI coding companion by AWS", url: "https://aws.amazon.com/codewhisperer/" },
  { name: "Blackbox AI", slug: "blackbox-ai", category: "Coding AI", description: "AI code search and autocomplete for developers", url: "https://www.blackbox.ai" },
  { name: "Anyscale", slug: "anyscale", category: "Coding AI", description: "Platform to build and scale AI applications", url: "https://www.anyscale.com" },
  { name: "LangChain", slug: "langchain", category: "Coding AI", description: "Framework for building LLM-powered applications", url: "https://www.langchain.com" },
  { name: "Pinecone", slug: "pinecone", category: "Data AI", description: "Vector database for high-performance AI apps", url: "https://www.pinecone.io" },
  { name: "Weights & Biases", slug: "weights-biases", category: "Data AI", description: "Developer tools for machine learning workflows", url: "https://wandb.ai" },
  { name: "Scale AI", slug: "scale-ai", category: "Data AI", description: "Data infrastructure for AI development", url: "https://scale.com" },
  { name: "Labelbox", slug: "labelbox", category: "Data AI", description: "Data labeling and management platform for AI", url: "https://labelbox.com" },
  { name: "Snorkel AI", slug: "snorkel-ai", category: "Data AI", description: "Data-centric AI platform for enterprise models", url: "https://snorkel.ai" },
  { name: "DataRobot", slug: "datarobot", category: "Data AI", description: "Enterprise AI platform for predictive modeling", url: "https://www.datarobot.com" },
  { name: "H2O.ai", slug: "h2o-ai", category: "Data AI", description: "Open-source AI and machine learning platform", url: "https://h2o.ai" },
  { name: "C3 AI", slug: "c3-ai", category: "Automation AI", description: "Enterprise AI software for digital transformation", url: "https://c3.ai" },
  { name: "Abacus.ai", slug: "abacus-ai", category: "Automation AI", description: "AI platform for real-time machine learning", url: "https://abacus.ai" },
  { name: "Harvey AI", slug: "harvey-ai", category: "Automation AI", description: "AI-powered legal research and analysis", url: "https://www.harvey.ai" },
  { name: "Ironclad AI", slug: "ironclad-ai", category: "Automation AI", description: "AI-powered contract lifecycle management", url: "https://ironcladapp.com" },
  { name: "Luminance", slug: "luminance", category: "Automation AI", description: "AI for legal document review and analysis", url: "https://www.luminance.com" },
  { name: "Casetext CoCounsel", slug: "casetext-cocounsel", category: "Automation AI", description: "AI legal assistant for research and drafting", url: "https://casetext.com/cocounsel" },
  { name: "Viz.ai", slug: "viz-ai", category: "Automation AI", description: "AI-powered medical imaging and care coordination", url: "https://www.viz.ai" },
  { name: "Paige AI", slug: "paige-ai", category: "Automation AI", description: "AI-powered pathology and cancer diagnostics", url: "https://paige.ai" },
  { name: "PathAI", slug: "pathai", category: "Automation AI", description: "AI-powered pathology for drug development", url: "https://www.pathai.com" },
  { name: "Tempus", slug: "tempus", category: "Data AI", description: "AI-powered precision medicine and data analysis", url: "https://www.tempus.com" },
  { name: "Insilico Medicine", slug: "insilico-medicine", category: "Automation AI", description: "AI-powered drug discovery and development", url: "https://insilico.com" },
  { name: "Exscientia", slug: "exscientia", category: "Automation AI", description: "AI-driven drug discovery and design", url: "https://www.exscientia.ai" },
  { name: "Recursion", slug: "recursion", category: "Automation AI", description: "AI-powered drug discovery and biology", url: "https://www.recursion.com" },
  { name: "BenevolentAI", slug: "benevolent-ai", category: "Automation AI", description: "AI-powered drug discovery and clinical trials", url: "https://www.benevolent.com" },
  { name: "AlphaFold", slug: "alphafold", category: "Research AI", description: "AI system that predicts protein structures", url: "https://alphafold.google" },
  { name: "Inflection AI", slug: "inflection-ai", category: "Chatbots", description: "Personal AI companion (Pi) for conversation", url: "https://pi.ai" },
  { name: "Mistral AI", slug: "mistral-ai", category: "Chatbots", description: "High-performance open-weight AI models", url: "https://mistral.ai" },
  { name: "Cohere", slug: "cohere", category: "Chatbots", description: "Enterprise AI platform for language processing", url: "https://cohere.com" },
  { name: "Groq", slug: "groq", category: "Coding AI", description: "LPU Inference Engine for ultra-fast AI", url: "https://groq.com" },
  { name: "Together AI", slug: "together-ai", category: "Coding AI", description: "Cloud platform for building and running AI", url: "https://www.together.ai" },
  { name: "Fireworks AI", slug: "fireworks-ai", category: "Coding AI", description: "Fast and efficient AI model inference", url: "https://fireworks.ai" },
  { name: "Elicit", slug: "elicit", category: "Research AI", description: "AI research assistant for literature review", url: "https://elicit.com" },
  { name: "Consensus", slug: "consensus", category: "Research AI", description: "AI search engine for scientific research", url: "https://consensus.app" },
  { name: "Scite.ai", slug: "scite-ai", category: "Research AI", description: "AI tool for discovering and evaluating research", url: "https://scite.ai", rating: 4.7, tags: ["Research", "Science", "Academic"] },
  { name: "Perplexity", slug: "perplexity", category: "Search AI", description: "AI-powered search engine that provides direct answers", url: "https://perplexity.ai", rating: 4.9, trending: true, tags: ["Search", "Answers", "Knowledge"] },
  { name: "Gamma", slug: "gamma", category: "Design AI", description: "AI tool for creating presentations, documents, and websites", url: "https://gamma.app", rating: 4.8, featured: true, tags: ["Presentations", "Design", "Slides"] },
  { name: "ElevenLabs", slug: "elevenlabs", category: "Audio AI", description: "Most realistic AI speech software", url: "https://elevenlabs.io", rating: 4.9, trending: true, tags: ["Voice", "TTS", "Audio"] },
  { name: "Cursor", slug: "cursor", category: "Coding AI", description: "The AI Code Editor built for programming with AI", url: "https://cursor.com", rating: 4.9, featured: true, tags: ["Coding", "IDE", "Development"] },
  { name: "Jasper", slug: "jasper", category: "Writing AI", description: "AI content platform that helps teams create content", url: "https://jasper.ai", rating: 4.7, tags: ["Marketing", "Copywriting", "Content"] },
  { name: "Descript", slug: "descript", category: "Video AI", description: "All-in-one video and podcast editing that's as easy as a doc", url: "https://descript.com", rating: 4.8, tags: ["Editing", "Podcast", "Video"] },
  { name: "Luma AI", slug: "luma-ai", category: "Video AI", description: "Create high-quality 3D and video content with AI", url: "https://lumalabs.ai", rating: 4.7, tags: ["3D", "Video", "Creative"] }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    title: "Best AI Tools for Students in 2026",
    slug: "best-ai-tools-for-students",
    excerpt: "Discover the most powerful AI tools that are helping students excel in their studies, from writing assistants to research engines.",
    content: "Full content here...",
    date: "2026-03-10",
    author: "AI Hub Team",
    category: "Education",
    tags: ["Students", "Productivity", "Writing"]
  },
  {
    title: "How to Automate Your YouTube Workflow with AI",
    slug: "youtube-automation-with-ai",
    excerpt: "Learn how to use AI for scriptwriting, video editing, and thumbnail creation to grow your channel faster.",
    content: "Full content here...",
    date: "2026-03-05",
    author: "Content Expert",
    category: "Video",
    tags: ["YouTube", "Automation", "Video AI"]
  },
  {
    title: "Top 10 Free AI Tools for Content Creators",
    slug: "free-ai-tools-for-content-creators",
    excerpt: "You don't need a big budget to create amazing content. Here are the best free AI tools available today.",
    content: "Full content here...",
    date: "2026-02-28",
    author: "Marketing Pro",
    category: "Marketing",
    tags: ["Free", "Content Creation", "Marketing AI"]
  }
];

